//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrossRateView
    {
        public System.Guid CrossRateId { get; set; }
        public System.Guid CurrencyIdFrom { get; set; }
        public System.Guid CurrencyIdTo { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public double Bid { get; set; }
        public double Ask { get; set; }
        public System.Guid OfficeId { get; set; }
        public string CurrencyFrom { get; set; }
        public string CurrencyTo { get; set; }
        public string Address { get; set; }
        public string Contacts { get; set; }
        public string Tittle { get; set; }
    }
}
