//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CurrencyDatabaseEntities : DbContext
    {
        public CurrencyDatabaseEntities()
            : base("name=CurrencyDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bank> Bank { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<CrossRate> CrossRate { get; set; }
        public virtual DbSet<Currency> Currency { get; set; }
        public virtual DbSet<Office> Office { get; set; }
        public virtual DbSet<CrossRateView> CrossRateView { get; set; }
        public virtual DbSet<OfficeView> OfficeView { get; set; }
    }
}
