//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficeView
    {
        public System.Guid OfficeId { get; set; }
        public System.Guid BankId { get; set; }
        public System.Guid CityId { get; set; }
        public string Address { get; set; }
        public string Contacts { get; set; }
        public string Tittle { get; set; }
        public string Bank { get; set; }
        public string City { get; set; }
    }
}
